# Generated by Django 4.1 on 2022-09-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_mywatchlistattribute_watched'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWatchListAttribute',
            new_name='MyWatchListItem',
        ),
    ]
